name: API CI

on:
  push:
    paths:
      - "apps/api/**"
      - ".github/workflows/api-ci.yml"
  pull_request:
    paths:
      - "apps/api/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: apps/api/requirements.txt

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends fonts-dejavu

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          PYPPETEER_HOME: ${{ runner.temp }}/pyppeteer
        run: pytest -q
